import {test,expect} from '@playwright/test'

const PARABANK = 'https://parabank.parasoft.com/parabank/index.htm';

const HEROKUAPP = 'https://the-internet.herokuapp.com/login';

const GooglePage = 'https://www.google.com/';

const SAUCEDEMO = 'https://www.saucedemo.com/'

test.describe('Day1_Session',() => {
    test('validate parabank title',async ({ page }) => {
    await page.goto(PARABANK);
    // await expect(page).toHaveTitle('ParaBank | Welcome | Online Banking');
    await expect(page).toHaveTitle(/ParaBank/);

    const registerLink =  page.getByRole('link',{ name: "Register"});
    await expect(registerLink).toBeVisible();
    await registerLink.click();
    //await page.pause(); //This line will open playwright inspector where we can record any desired locators
    //locator('[id="customer.firstName"]')
    await page.locator('[id="customer.firstName"]').fill('John');
    //await page.pause();
    //Below code is generated by playwright inspector. It is not a good practice to use this code in your test script. Instead, use getByRole, getByLabel, getByText, getByPlaceholder, etc.
    await page.locator('[id="customer.lastName"]').click();
    await page.locator('[id="customer.lastName"]').fill('doe');
    await page.locator('[id="customer.address.street"]').click();
    await page.locator('[id="customer.address.street"]').fill('usa');
    await page.locator('[id="customer.address.city"]').click();
    await page.locator('[id="customer.address.city"]').fill('california');
    await page.locator('[id="customer.address.state"]').click();
    await page.locator('[id="customer.address.state"]').fill('new york');
    await page.locator('[id="customer.address.zipCode"]').click();
    await page.locator('[id="customer.address.zipCode"]').fill('48929492');
    await page.locator('[id="customer.phoneNumber"]').click();
    await page.locator('[id="customer.phoneNumber"]').fill('249749234');
    // await page.pause();
    });
});

